### ISSUE TITLE
Semantic error at paths./solution/mutiple_choice/{task_id}

### ISSUE THREAD

**Issue by Korkmatik** [E-Edu/draft-documents#3]
Hi,

if I copy and paste the [YAML](https://github.com/E-Edu/draft-documents/blob/master/swagger/task.yaml) file into the [swagger editor](https://editor.swagger.io/) I get this error:

![grafik](https://user-images.githubusercontent.com/39222224/78188527-ae70ab00-7470-11ea-998c-cd17e2662c75.png)

Could you please check this? Thanks in advance!

**Comment by adamane** [comment]
Little Tip: you dont need to paste the code into the swagger editor, you can use one of the links in the readme.md in the root of the repo.
