### ISSUE TITLE
JSON issue report-ms 

### ISSUE THREAD

**Issue by n1xqe** [E-Edu/draft-documents#4]
Old:
[
  {
    "ticket_id": "string",
    "task_id": "string",
    "sender": "string",
    "title": "string",
    "body": "string",
    "ticket_type": "string"
  }
]
New:
{
  {
    "ticket_id": "string",
    "task_id": "string",
    "sender": "string",
    "title": "string",
    "body": "string",
    "ticket_type": "string"
  }
}
(pls fix)

**Comment by n1xqe** [comment]
task_id int or str?

**Comment by adamane** [comment]
We merged into E-Edu/concepts, please create your issue there.
